[features]
seeds = false
skip-lint = false

[programs.localnet]
casinc = "5V4zAh34TPQdrbXqBNbEbW7o9zknXceM8fVK5VK5HnM7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
